# Generated by Django 5.0.2 on 2024-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_clinte_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordem',
            options={'verbose_name_plural': 'ordens'},
        ),
        migrations.AddField(
            model_name='produto',
            name='e_saldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
